name: Daily Islamic Short
on:
  schedule:
    - cron: "30 22 * * *"   # 03:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - run: python scripts/generator.py
      - run: echo "Ready!"
